# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYNc9FUg7oO6fED2CRXRdC56WfbtnAKL
"""

import streamlit as st
import joblib
import numpy as np
import requests
import os

# Google Drive Direct Links
MODEL_URL = 'https://docs.google.com/uc?export=download&id=1CWb5VulFadBdjgFCaRyacHttK8QsyPat'
SCALER_URL = 'https://docs.google.com/uc?export=download&id=1q5ONzfQ4xyoNzntB9X61Cqm94eRjvm7W'

# File download karne ka function
def download_file(url, filename):
    if not os.path.exists(filename):
        response = requests.get(url)
        with open(filename, 'wb') as f:
            f.write(response.content)

# Files download aur load karo
download_file(MODEL_URL, 'churn_model.pkl')
download_file(SCALER_URL, 'scaler.pkl')

model = joblib.load('churn_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("Bank Customer Churn Predictor")

# Input fields
age = st.number_input("Age", 18, 100)
balance = st.number_input("Balance", 0, 500000)

if st.button("Predict"):
    # Input data ko array mein badlo
    input_data = np.array([[age, balance]])

    # Data ko scale karna ZAROORI hai
    input_data_scaled = scaler.transform(input_data)

    # Prediction
    prediction = model.predict(input_data_scaled)

    if prediction[0] == 1:
        st.write("Customer will Churn.")
    else:
        st.write("Customer will not Churn.")