# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYNc9FUg7oO6fED2CRXRdC56WfbtnAKL
"""

# Install Streamlit if not already installed
!pip install streamlit

import streamlit as st
import joblib
import numpy as np


# Load model and scaler with joblib
model = joblib.load('churn_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("Bank Customer Churn Predictor")

age = st.number_input("Age", 18, 100)
balance = st.number_input("Balance", 0, 500000)

if st.button("Predict"):
    input_data = np.array([[age, balance]])
    scaled_data = scaler.transform(input_data)
    prediction = model.predict(scaled_data)

    if prediction[0] == 1:
        st.error("Customer is likely to CHURN!")
    else:
        st.success("Customer is LOYAL.")